[package]
name = "lr2021"
version = "0.14.0"
edition = "2024"
license = "MIT"
description = "Driver for Semtech LR2021"
repository = "https://github.com/TheClams/lr2021"
readme = "Readme.md"
categories = ["embedded", "no-std"]
keywords = ["driver", "LR2021", "transceiver"]

[features]
defmt = ["dep:defmt"]
# Enable 2.4Ghz RF path (LR2021/LR2022)
rf2g4 = []
# Enable Adavanced FSK like FLRC/Zigbee/ZWave (LR2021)
fskadv = []
# Default correspond to LR2021
default = ["rf2g4","fskadv"]

[dependencies]

embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-embedded-hal = { version = "0.5.0" }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0"

defmt = { version = "1.0.1", optional = true }

# Disable test when running all target to avoid issue with rust-analyzer
[lib]
test = false
doctest = false
bench = false
